module.exports = {
  ONBOARD_NAME: 'ONBOARD_NAME',
  ONBOARD_LANGUAGE: 'ONBOARD_LANGUAGE',
  ONBOARD_ACTIVITY: 'ONBOARD_ACTIVITY',
  ONBOARD_DAYS: 'ONBOARD_DAYS',
  ONBOARD_TIME: 'ONBOARD_TIME',
  ONBOARD_BLOCKER: 'ONBOARD_BLOCKER',
  ONBOARD_VISION: 'ONBOARD_VISION',
  ONBOARD_COMMITMENT: 'ONBOARD_COMMITMENT',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  ACTIVE: 'ACTIVE',
  AWAITING_CHECKIN_FOLLOWUP: 'AWAITING_CHECKIN_FOLLOWUP',
  COMPLETED: 'COMPLETED',
};
